[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv ; <-- ADD THIS LINE

; This matches the Serial.begin(115200) in your code
monitor_speed = 115200

lib_deps = 
	paulstoffregen/OneWire
	milesburton/DallasTemperature
	adafruit/Adafruit ADS1X15
	https://github.com/mobizt/Firebase-ESP-Client.git
	esphome/AsyncTCP-esphome @ ^2.0.0
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
    bblanchon/ArduinoJson @ ^6.21.3